name: Open Contracting Data Standard
description: Updates from the development of an Open Contracting Data Standard
markdown: redcarpet
redcarpet:
    extensions: [with_toc_data]
pygments: true
baseurl: /
